apiVersion: apps/v1
kind: Deployment
metadata:
  name: dailyblog
spec:
  replicas: 3
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 1
  #     maxSurge: 1
  # minReadySeconds: 5
  selector:
    matchLabels:
      app: dailyblog
  template:
    metadata:
      labels:
        app: dailyblog
    spec:
      containers:
      - name: dailyblog
        image: jayabrata180/dailyblog
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
          protocol: TCP

